name: build-wasm
on: [push]
jobs:
  build:
    name: 'Build Production Bundle'
    runs-on: ubuntu-latest

    env:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

    steps:
      - uses: actions/checkout@v3
      - run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            site/wasm

      - name: Build WASM Bundle
        run: |
          cargo install wasm-pack --no-default-features --locked
          cd site/wasm && wasm-pack build

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install Pnpm
        run: npm install -g pnpm

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: pnpm-store-${{ hashFiles('site/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-

      - name: Install Node dependencies
        run: cd site && pnpm install && pnpm run build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: site/dist

  deploy:
    name: 'Deploy to Github Pages'
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v2
